spring:
  profiles:
    # 默认的启动配置文件
    active: local

mybatis:
  configuration:
    # 开启驼峰命名自动转换
    map-underscore-to-camel-case: true
    

# 打印 mybatis 执行的 sql 语句
logging:
  level:
    com:
      ydm:
        bootlast:
          dao: debug
