spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
server:
  port: 8084
